# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=1, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
            preserve_default=False,
        ),
    ]
